version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./certs:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - REACT_APP_API_URL=http://ailogo.world:8000
    ports:
      - '3000:3000'
      - '443:443'

networks:
  default:
    external:
      name: ailogo.world
