version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./certs:/etc/nginx/ssl
    ports:
      - '3000:3000'
      - '443:443'
    command: >
      sh -c "npm run "



version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

networks:
  backend:
    external:
      name: docker-compose-network  # FastAPI와 Langserve 컨테이너가 사용하는 네트워크 이름
