version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - REACT_APP_API_URL=https://ailogo.world
    ports:
      - '80:80'
      - '443:443'

networks:
  default:
    external:
      name: ailogo.world
